# .travis.yml
# Configure Travis CI service to build Sentilo platform, http://github.com/sentilo/sentilo
#
sudo: false

language: java

jdk:
  - oraclejdk8
  
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura
